// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Hero() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section><div class=\"my-32 mx-32 px-32 flex flex-col justify-between items-start gap-y-8\"><span class=\"mt-8 mb-16 text-white text-8xl font-bold\">Make Your Software<br>Vision a Reality</span> <span class=\"text-white font-bold text-5xl\">Pro tools created with <a href=\"#for-developers\" class=\"text-purple-600 underline hover:text-white\">&#123;developers&#125;</a>,<br><a href=\"#for-teams\" class=\"text-cyan-400 underline hover:text-white\">teams</a>, and <a href=\"#for-businesses\" class=\"text-pink-400 underline hover:text-white\">businesses</a> in mind</span></div></section><section id=\"for-developers\" class=\"bg-cyan-900 h-[400px]\"></section><section id=\"for-teams\" class=\"bg-orange-600 h-[400px]\"></section><section id=\"for-businesses\" class=\"bg-green-600 h-[400px]\"></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
