// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex shadow-md justify-between items-center px-8 py-2\"><!-- Logo --><div class=\"font-bold\">NewsAggregator</div><!-- pages --><div class=\"flex flex-grow justify-end items-center space-x-12 mx-16 px-16\"><a href=\"#\" class=\"text-slate-500 hover:text-gray-300\">Docs</a> <a href=\"#\" class=\"text-slate-500 hover:text-gray-300\">Download</a> <a href=\"#\" class=\"text-slate-500 hover:text-gray-300\">About Us</a> <a href=\"#\" class=\"text-slate-500 hover:text-gray-300\">Support</a></div><!-- buttons --><a href=\"https://github.com/OOPProject20232/NewsAggregatorClient\"><button type=\"button\" class=\"flex justify-center items-center space-x-8 bg-black text-white rounded-full p-2 hover:bg-gray-300\"><img src=\"/assets/images/github-logo.svg\" class=\"w-5 h-5\"> Github</button></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
